name: Bettercolor
version: '${project.version}'
main: com.bettercolor.chat.bettercolor.Bettercolor
api-version: 1.16
depend: []
authors: [ rickSanchez ]
description: Plugin que colorea con degradados
commands:
  gradient:
    description: Hellow world!
